.TH "Version of the BrlAPI library" 3 "7 Oct 2009" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Version of the BrlAPI library \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBRLAPI_RELEASE\fP   '0.5.4'"
.br
.ti -1c
.RI "#define \fBBRLAPI_MAJOR\fP   0"
.br
.ti -1c
.RI "#define \fBBRLAPI_MINOR\fP   5"
.br
.ti -1c
.RI "#define \fBBRLAPI_REVISION\fP   4"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BRLAPI_MAJOR   0"
.PP
Library major version. 
.SS "#define BRLAPI_MINOR   5"
.PP
Library minor version. 
.SS "#define BRLAPI_RELEASE   '0.5.4'"
.PP
Library version. 
.SS "#define BRLAPI_REVISION   4"
.PP
Library revision. 
